# Change these first
owner: QuentinPhilipp # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: blog
    url: https://blog.quentinphilipp.fr
  - name: Equivallee Booking
    url: https://equivallee.quentinphilipp.fr

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
